### ISSUE TITLE
error when initializing

### ISSUE THREAD

**Issue by drma-dev** [AspNetMonsters/Blazor.Geolocation#17]
I am using the latest stable version of blazor.

when installing the latest stable version of this component, it generates an unknown error.

when installing the latest beta, the following error occurs:

Could not find 'AspNetMonsters' in 'window'. Error: Could not find 'AspNetMonsters' in 'window'. at https://localhost:44313/_framework/blazor.server.js:8:30748 at
 Array.forEach (<anonymous>) at p (https://localhost:44313/_framework/blazor.server.js:8:30709) at https://localhost:44313/_framework/blazor.server.js:8:31416 at 
 new Promise (<anonymous>) at e.beginInvokeJSFromDotNet (https://localhost:44313/_framework/blazor.server.js:8:31390) at https://localhost:44313/_framework/blazor.server.js:1:19202 at 
 Array.forEach (<anonymous>) at e.invokeClientMethod (https://localhost:44313/_framework/blazor.server.js:1:19173) at 
 e.processIncomingData (https://localhost:44313/_framework/blazor.server.js:1:17165

**Comment by Muppets** [comment]
+1 for release version of blazor. I saw some commits relating to rolling out a version using the release bits, nuget update coming with it?

Love the package btw, great work!

**Comment by ummerland** [comment]
I have this error as well.
Is there something to get it working?

**Comment by ummerland** [comment]
Ok so i did two things to get it running:

- copied Location.js and Location.js.map from this repository to the wwwroot directory of the VS-solution

- edited the script tag in _Host.cshtml:
<script src="/Location.js"></script>

**Comment by MichaelSL** [comment]
While there is a workaround available, it would be great to include js files in the NuGet.

**Comment by ummerland** [comment]
You are right, maybe @stimms  can help us along

**Comment by Styx665** [comment]
any news on this?

**Comment by drma-tech** [comment]
@Styx665 I am using this component now. has many things available.

[https://github.com/RemiBou/BrowserInterop](https://github.com/RemiBou/BrowserInterop)
