### ISSUE TITLE
Not Working in Blazor 0.6.0

### ISSUE THREAD

**Issue by orominioo** [AspNetMonsters/Blazor.Geolocation#4]
Try running it on Blazor 0.6.0 but get error
![unknjown](https://user-images.githubusercontent.com/16209229/46544225-0c7afd00-c891-11e8-8e8b-d02718709640.png)
![unknown](https://user-images.githubusercontent.com/16209229/46544232-113fb100-c891-11e8-9c63-a1693940304e.png)

**Comment by dpaquette** [comment]
Yes, I need to publish an update to get this working on 0.6. Not sure when I will have time but hopefully in the next week or so

**Comment by stimms** [comment]
I believe the latest release will work on 0.6. I only tested against 0.7. It was fixed by #5
